[server]
headless = true
# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 100

[browser]
# serverPort = 9045

[theme] 
# base="dark"
primaryColor="purple"
textColor="#262730"

[client]
showErrorDetails = true

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "error"