[server]
serverPort = 9045
headless = true

[theme] 
primaryColor = "#3A86FF"

[file]
# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 10

[client]
showErrorDetails = true

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "error"