[server]
headless = true
# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 10

[browser]
# serverPort = 9045

[theme] 
primaryColor = "#3A86FF"

[client]
showErrorDetails = true

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "error"